
import { YPPReport } from './YPPAnalyzer';

/**
 * Report Generator
 * Generates a markdown report from the YPP analysis.
 */

export const generateMarkdownReport = (report: YPPReport): string => {
    const { overallScore, viralStatus, metrics, insights, actions } = report;

    const getStatusIcon = (status: string) => {
        switch (status) {
            case 'Good': return '✅';
            case 'Warning': return '⚠️';
            case 'Critical': return '❌';
            default: return '❓';
        }
    };

    return `
# 📊 YPP Algorithm Analysis Report
**Generated**: ${new Date().toLocaleString()}

## 🚀 Core Status
- **Overall Score**: ${overallScore}/100
- **Viral Status**: **${viralStatus.toUpperCase()}**
  > ${viralStatus === 'Viral' ? '🔥 Content is exploding! Keep momentum.' :
            viralStatus === 'Rising' ? '📈 Good growth signals. Optimize slightly.' :
                viralStatus === 'Seeding' ? '🌱 Initial phase. Focus on quality and consistency.' :
                    '💤 Content is dormant. Needs major overhaul.'}

---

## 📈 Key Metrics Analysis

| Metric | Value | Target | Status |
|--------|-------|--------|--------|
| **APV (Retention)** | ${metrics.apv.value}% | ${metrics.apv.target}% | ${getStatusIcon(metrics.apv.status)} |
| **Shorts Feed** | ${metrics.shortsFeed.value}% | ${metrics.shortsFeed.target}% | ${getStatusIcon(metrics.shortsFeed.status)} |
| **Engagement Rate** | ${metrics.engagement.value.toFixed(1)}% | ${metrics.engagement.target}% | ${getStatusIcon(metrics.engagement.status)} |
| **CTR** | ${metrics.ctr.value}% | ${metrics.ctr.target}% | ${getStatusIcon(metrics.ctr.status)} |

---

## 💡 Insights & Optimization

### 🔍 Key Insights
${insights.length > 0 ? insights.map(i => `- ${i}`).join('\n') : '- No critical issues found. Good job!'}

### 🛠️ Recommended Actions
${actions.length > 0 ? actions.map(a => `- [ ] ${a}`).join('\n') : '- Continue with current strategy.'}

---
*Generated by AI Smart Creator - YPP Algorithm Engine*
`;
};
