#!/usr/bin/env node

/**
 * Quick OAuth Setup Script
 * 
 * Helps users quickly set up OAuth authentication for the AI Content Platform.
 * 
 * Usage:
 *   node scripts/setup-oauth.js
 */

import fs from 'fs';
import path from 'path';
import { createInterface } from 'readline';
import { execSync } from 'child_process';

const rl = createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => {
    rl.question(query, answer => resolve(answer));
  });
}

async function setupOAuth() {
  console.log('\n' + '='.repeat(60));
  console.log('🔐 OAuth Quick Setup');
  console.log('='.repeat(60));
  console.log('\nThis script will help you set up Google OAuth for the AI Content Platform.');
  console.log('You will need your Google Client ID and Client Secret.');
  console.log('\nGet them from: https://console.cloud.google.com/apis/credentials');
  console.log('='.repeat(60) + '\n');

  try {
    // Step 1: Check if server package.json exists
    const serverDir = path.join(process.cwd(), 'server');
    const serverPackageJson = path.join(serverDir, 'package.json');

    if (!fs.existsSync(serverPackageJson)) {
      console.error('❌ Server directory not found. Please run this script from the project root.');
      process.exit(1);
    }

    // Step 2: Install server dependencies
    console.log('\n📦 Installing server dependencies...');
    try {
      execSync('cd server && npm install', { stdio: 'inherit' });
      console.log('✅ Dependencies installed\n');
    } catch (error) {
      console.error('❌ Failed to install dependencies');
      process.exit(1);
    }

    // Step 3: Get OAuth credentials
    console.log('\n📝 Enter your Google OAuth credentials:');
    console.log('(Leave empty to skip OAuth setup)\n');

    const clientId = await question('Google Client ID: ');
    if (!clientId) {
      console.log('\n⚠️  Skipping OAuth setup. You can still use API Key method.');
      console.log('See OAUTH_SETUP.md for details.\n');
      rl.close();
      return;
    }

    const clientSecret = await question('Google Client Secret: ');
    
    if (!clientSecret) {
      console.error('❌ Client Secret is required');
      process.exit(1);
    }

    // Step 4: Configure ports
    console.log('\n🔧 Port configuration:');
    console.log('OAuth Server (backend): http://localhost:51122');
    console.log('Frontend App: http://localhost:4000\n');

    const oauthPort = await question('OAuth Server Port [51122]: ') || '51122';
    const frontendPort = await question('Frontend Port [4000]: ') || '4000';

    // Step 5: Create server .env file
    const serverEnvContent = `
# OAuth Server Configuration
# Generated by setup-oauth.js on ${new Date().toISOString()}

# Google OAuth2 Credentials
GOOGLE_CLIENT_ID=${clientId}
GOOGLE_CLIENT_SECRET=${clientSecret}

# OAuth Callback URI
GOOGLE_REDIRECT_URI=http://localhost:${oauthPort}/oauth-callback

# Backend Server Port
OAUTH_SERVER_PORT=${oauthPort}

# Frontend App URL (for CORS)
FRONTEND_URL=http://localhost:${frontendPort}

# Frontend OAuth Callback URL
FRONTEND_OAUTH_CALLBACK=http://localhost:${frontendPort}/oauth-callback
`;

    const serverEnvPath = path.join(serverDir, '.env');
    fs.writeFileSync(serverEnvPath, serverEnvContent.trim());
    console.log('✅ Server .env file created');

    // Step 6: Update project .env file
    const projectEnvPath = path.join(process.cwd(), '.env.local');
    const projectEnvContent = `
# AI Content Platform - Environment Configuration
# Generated by setup-oauth.js on ${new Date().toISOString()}

# Gemini API Key (Optional - for direct API access)
# Get from: https://makersuite.google.com/app/apikey
# GEMINI_API_KEY=your-gemini-api-key-here

# OAuth Server URL
OAUTH_SERVER_URL=http://localhost:${oauthPort}

# Development Mode
NODE_ENV=development
`;

    if (fs.existsSync(projectEnvPath)) {
      const backup = fs.readFileSync(projectEnvPath, 'utf-8');
      fs.writeFileSync(projectEnvPath + '.backup', backup);
      console.log('📝 Existing .env.local backed up');
    }

    fs.writeFileSync(projectEnvPath, projectEnvContent.trim());
    console.log('✅ Project .env.local file created');

    // Step 7: Update package.json scripts
    const packageJsonPath = path.join(process.cwd(), 'package.json');
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

    if (!packageJson.scripts['oauth:server']) {
      packageJson.scripts['oauth:server'] = 'cd server && npm start';
      packageJson.scripts['oauth:dev'] = 'cd server && npm run dev';
      packageJson.scripts['dev:full'] = 'npm run oauth:dev & npm run dev';
      
      fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
      console.log('✅ Package.json scripts updated');
    }

    // Step 8: Summary
    console.log('\n' + '='.repeat(60));
    console.log('✅ OAuth Setup Complete!');
    console.log('='.repeat(60));
    console.log('\nNext steps:\n');
    console.log('1. Start OAuth Server:');
    console.log('   npm run oauth:dev');
    console.log(`   → Running at http://localhost:${oauthPort}`);
    console.log('\n2. Start Frontend App:');
    console.log('   npm run dev');
    console.log(`   → Running at http://localhost:${frontendPort}`);
    console.log('\n3. Or start both at once:');
    console.log('   npm run dev:full');
    console.log('\n4. Test OAuth:');
    console.log('   cd server && npm test');
    console.log('\n5. For detailed instructions, see:');
    console.log('   - OAUTH_SETUP.md');
    console.log('   - server/README.md');
    console.log('='.repeat(60) + '\n');

    rl.close();
  } catch (error) {
    console.error('❌ Setup failed:', error.message);
    process.exit(1);
  }
}

setupOAuth();
